In [6]:
import numpy as np
import random
data=np.array([random.randint(1,21) for i in range(20)])
print(data)

[ 4  7  7 18 11 10  7 12 17 10 18 10  2 17  4 11  8  4 13 11]


In [8]:
#使用数组添加
data=np.append(data,[1,2,10,11])
print(data)

[ 4  7  7 18 11 10  7 12 17 10 18 10  2 17  4 11  8  4 13 11  1  2 10 11]


In [11]:
#使用数组删除
data=data[data[:]!=4]
print(data)
data=np.delete(data,4)
print(data)

[ 7  7 18 11 10  7 12 17 10 18 10  2 17 11  8 13 11  1  2 10 11]
[ 7  7 18 11  7 12 17 10 18 10  2 17 11  8 13 11  1  2 10 11]


In [12]:
#使用数组去重
data=np.unique(data)
print(data)

[ 1  2  7  8 10 11 12 13 17 18]
