In [37]:
import numpy as np
arr=np.arange(24,dtype=float).reshape(4,6)
print(arr.ndim)
print(arr)

2
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


In [38]:
import random
for i in range(5):
    arr[random.randint(0,3),random.randint(0,5)]=np.nan
print(arr)
print('-'*50)
for i in range(arr.shape[1]):
    temp_col=arr[:,i]
    num_nan=np.count_nonzero(temp_col!=temp_col)
    if num_nan:
        temp_col[np.isnan(temp_col)]=np.mean(temp_col[temp_col==temp_col])
print(arr)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7. nan  9. 10. 11.]
 [nan nan nan 15. nan 17.]
 [18. 19. 20. 21. 22. 23.]]
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7. 11.  9. 10. 11.]
 [ 8.  9. 11. 15. 12. 17.]
 [18. 19. 20. 21. 22. 23.]]
